name: Deploy react app
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "12.x" ]
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install package
        run: npm install
      - name: registry github user
        run: |
          git config --global user.email <jelo2021@gmail.com>
          git config --global user.name <eduardolizarazu>
      - name: deploy the app
        run: npm run deploy
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
